spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bit
    #url: jdbc:mariadb://mariadb/finanz
    username: root
    password: finanz
    driver-class-name: org.mariadb.jdbc.Driver

config:
  security:
    oauth:
      client:
        id: client_bit
        secret: 12345
      jwt:
        key: mi_firma_super_segura