spring:
  application:
    name: bit
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 30
        generate_statistics: false
        order_inserts: true
    hibernate:
      ddl-auto: none #update
  flyway:
    #enabled: false #comment
    baselineOnMigrate: true
    baselineDescription: baseline_migration
    baselineVersion: 1.0
  output:
    ansi:
      enabled: always

hibernate:
  cache:
    use_second_level_cache: true
    region:
      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    provider_class: net.sf.ehcache.hibernate.EhCacheProvider